management:
  endpoints:
    health:
      enabled: true
    web.base-path: /

spring:
  application:
    name: vault-demo
  cloud:
    vault:
      generic:
        enabled: false
      host: vault.vault.svc.cluster.local
      port: 8200
      scheme: http
      authentication: KUBERNETES
      kubernetes:
        role: myapprole
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
      config:
        order: 10

logging:
  level:
    org:
      springframework: info
